### ISSUE TITLE
0.6.5 Backup fails, no /data/queue

### ISSUE THREAD

**Issue by chsims1** [macmpi/volumio-plugins#1]
I did a factory reset before installing the plugin, and added my DAC to the UI, but did nothing else.

Backup fails because there is no /data/queue at this point.

> Jul 13 07:42:31 volumio volumio[930]: /bin/tar: /data/queue: Cannot stat: No such file or directory

Obviously this is pretty much a false scenario for most users, but someone will do it :)

**Comment by macmpi** [comment]
Yes, in such case user would rather restore a config than back it up, but I get the point: this one will be easy to fix, thanks for reporting.

While at it, in such circumstances are all other folders present (playlist, favourites, configuration, albumart)?

**Comment by chsims1** [comment]
Yep, the others are there.

> volumio@volumio:/data$ ls
INTERNAL  albumart  backgrounds  configuration  favourites  playerstate  playlist  plugins

**Comment by macmpi** [comment]
fixed as per 0.6.7
You may close the issue once you checked it is resolved.
Thanks.

**Comment by chsims1** [comment]
Yep, that sorts it, ty.

Two other things occur to me:
(1) You really should prompt user to reboot after restoring data, or possibly even just do it;
(2) Not part of the /data structure, but it would be nice if you could add the player name into the archive too.

**Comment by macmpi** [comment]
**re 1**: yes I'm considering it: actually rather relaunch Volumio app than a full reboot (`sudo systemctl restart volumio`)

**re 2**: I'll look at it, but the thing is, if we depart from core `/data ` stuff, we'll get into many Linux system config files, which may open multiple cans of worms... (like when people edit them manually).
Even `/data/configuration` is not ideal actually as some of the contained settings are not applied by just restoring: some switches need to be flipped so that settings get into the system again...(i2s, etc)
